---
# tasks file for vector-role
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-1.x86_64.rpm"
    dest: "./vector-1.x86_64.rpm"
    mode: 0664
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name:
      - vector-1.x86_64.rpm
  notify: Start Vector
  changed_when: true
- name: Vector config template
  become: true
  ansible.builtin.template:
    src: ./templates/vector.j2
    dest: /etc/vector/vector.toml
    mode: 0644